language: objective-c
osx_image: xcode12
xcode_project: YCDownloadSessionDemo.xcworkspace
xcode_scheme: YCDownloadSessionDemo

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version
- ruby -v
- gem source -l

script:
- set -o pipefail
- bundle install
- bundle exec pod install
- xcodebuild clean build -workspace "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty
